
name: publish

on:
  push:
    paths:
      - 'Dockerfile'
      - '.github/workflows/build_env.yml'

jobs:
  publish-docker-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the Docker image
      run: |
        docker build . --tag ghcr.io/krmnn/rp2040-vult-build-env:latest
        docker run ghcr.io/krmnn/rp2040-vult-build-env:latest
        docker push ghcr.io/krmnn/rp2040-vult-build-env:latest